#!/bin/bash

NAME="Dart"
BASE_REPO=node
VARIANTS=(browsers)
IMAGE_CUSTOMIZATIONS='
RUN apt-get update
RUN apt-get -y install apt-transport-https
RUN sh -c "curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"
RUN sh -c "curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list"
RUN apt-get update
ENV PATH=/usr/lib/dart/bin:$PATH
RUN apt-get -y install dart
'

source ../shared/images/generate.sh
