#!/bin/bash

NAME="Dart"
BASE_REPO=node
VARIANTS=(browsers)
IMAGE_CUSTOMIZATIONS='
RUN apt-get update
RUN apt-get -y install apt-transport-https
RUN sh -c "curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"
RUN sh -c "curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list"
RUN apt-get update
ENV PATH=/usr/lib/dart/bin:$PATH
RUN apt-get -y install dart
WORKDIR /opt
RUN wget https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.3/dartium/dartium-linux-x64-release.zip && unzip dartium-linux-x64-release.zip && rm dartium-linux-x64-release.zip
RUN mv dartium-linux-x64-stable-1.24.2.0/ dartium && ln -s /opt/dartium/chrome /bin/dartium
'

source ../shared/images/generate.sh
